### ISSUE TITLE
Test site on Safari, iPhone and tablet

### ISSUE THREAD

**Issue by markpfaff** [markpfaff/WSMA#52]
Please note the page you're on, screen size and any other info like how the bug was triggered etc
Bugs:

**Comment by Atiagina** [comment]
## OS X El Capitan - Version 9.0.1 (11601.2.7.2)

**Safari 1366x768:**
all pages: footer content is not aligned 
home page - 3 columns height span content length only;
dropdown of 'Media' drops under the rectangle rom the picture
<img width="461" alt="screen shot 2015-12-01 at 4 06 57 pm" src="https://cloud.githubusercontent.com/assets/10586909/11518392/9c2e807c-9845-11e5-9871-6d7a44bdb455.png">
news page - do we want to have older posts link to be under sidebar? it looks like it'd better be under the posts 
<img width="865" alt="screen shot 2015-12-01 at 4 13 35 pm" src="https://cloud.githubusercontent.com/assets/10586909/11518485/85a8b24a-9846-11e5-8d30-e88f3bda6b03.png">

## iPhone  5s iOS 9.1

**Safari:**
- menu hamburger and search icon should be inline with the logo, right?
- dropdown menu doesn't work
- when we open the menu, suddenly a search bar appears under it too :)
  ![image1-2](https://cloud.githubusercontent.com/assets/10586909/11518589/ac3aeae4-9847-11e5-9a1f-a7fd2c94beaf.PNG)
- rectangle on the picture disappears, but text stays and overlaps with other text on the page
  ![image1-3](https://cloud.githubusercontent.com/assets/10586909/11518743/c565ab52-9848-11e5-9b2e-86344583bb31.PNG)
- on the news page the footer looks weird
  ![image3](https://cloud.githubusercontent.com/assets/10586909/11518667/5abd7b72-9848-11e5-861c-9a31d143c699.JPG)
- on other pages footer content just not centered
  ![image4](https://cloud.githubusercontent.com/assets/10586909/11518746/ceff474a-9848-11e5-802d-16ae11d18ef4.PNG)
- form on the contact page
  ![image2](https://cloud.githubusercontent.com/assets/10586909/11518664/56630286-9848-11e5-864f-de761d2bedac.PNG)

**Comment by Atiagina** [comment]
sorry for huge images! :) I continue:

**Comment by Atiagina** [comment]
## iPhone 5s iOS 9.1

**Chrome:**

all the issues for Safari I can see on Chrome too

## iPad Mini iOS 9.1

**768x1024**

**Safari:**
home page:
- rectangle from the picture overlaps other divs
- 3 columns height span content length only
- Latest photos header from the Latest media goes under the picture
  ![image3](https://cloud.githubusercontent.com/assets/10586909/11518923/62c82928-984a-11e5-894c-81c8c225cb24.PNG)
- footer contact is not aligned
  Enroll page (and all other similar pages): 
- sidebar goes under the content
  ![image2-2](https://cloud.githubusercontent.com/assets/10586909/11518918/58970834-984a-11e5-91e2-6d357344501d.PNG)

Media page:
- broken layout
  ![image1-4](https://cloud.githubusercontent.com/assets/10586909/11518917/52a411ec-984a-11e5-9a42-066b634d3fe2.PNG)

Dropdown menu doesn't work.

**Comment by Atiagina** [comment]
## iPad Mini iOS 9.1

**768x1024**

Also just realized that there is a thin yellow line on the right side of the home page in Safari. I can see it both in Chrome and Safari on my iPad mini.

**Chrome:**
Footer. Whereas in Safari footer content is not aligned but still appears in columns, in Chrome it is in columns only on the home page. All other pages are just one column. On the picture you can see an example from the news page with the yellow line on the right side. All other pages are without yellow line, but with one column footer (except home).

![image1-5](https://cloud.githubusercontent.com/assets/10586909/11519100/1721d026-984c-11e5-9af7-a73d92cb2378.PNG)

how the footer looks on the home page in the same browser:

![image2-3](https://cloud.githubusercontent.com/assets/10586909/11519103/2479aa00-984c-11e5-8c5c-73beacafd4b6.PNG)
