### ISSUE TITLE
Test on Firefox, Chrome, and Android and Edge

### ISSUE THREAD

**Issue by markpfaff** [markpfaff/WSMA#54]
Please note the page you're on, screen size and any other info like how the bug was triggered etc
Bugs:

**Comment by ttalevich** [comment]
<p>OS X El Capitan - Chrome 46.0.2490.86</p>

<p>OS X El Capitan - Firefox 40.0.3</p>

<p>Android 5.1.1 (Touchwiz) - Chrome Beta 47.0.2526.69</p>

<p>Desktop window size approx ~1720px wide</p>

<h2>Firefox</h2>
- [x] Home - 3 columns height span whole length
- [x] Nav dropdown on hover does NOT work

<h2>Chrome</h2>
- [x] Home CTAs - columns have uneven height

<h2>Chrome / Firefox</h2>
- [x] Sidebar on instrument pages is spaced below the orange description opposed to the top of the page
- [x] Calendar page bottom plugin controls display under orange container
- [x] News page footer is sized wrong
- [x] Search result heading background spans sidebar height, pushes results far down the page

<h2>Chrome on Android</h2>
- [x] Footer content alignment not centered
- [x] Nav - cannot access subnav, will go to main page (i.e. tapping About will not activate the subnav, and just take you to the About page)
- [x] Instruments page images arranged weird (design preference), first row (3) of images sized smaller than rest
- [x] News page footer width still wrong

**Comment by markpfaff** [comment]
I switched it ti checkboxes so I could check off as I fixed things.
Not sure what "Home - 3 columns height span whole length" means
Not sure what " Home - 3 columns height span content length only" means

**Comment by ttalevich** [comment]
The 3 yellow columns on the home page (Latest News, Media, Classes). On Firefox the background spans further than the content (making the 3 boxes appear the same height), whereas on Chrome the background only shows around the content (making the boxes different heights)

**Comment by markpfaff** [comment]
Gotcha! Thanks
